# Generated by Django 5.2.4 on 2025-07-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('vote_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vote_count', models.IntegerField()),
            ],
        ),
    ]
