# Generated by Django 5.2.4 on 2025-07-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='other',
            field=models.TextField(default='domyslna 1'),
            preserve_default=False,
        ),
    ]
