# Generated by Django 5.2.4 on 2025-07-05 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='other',
        ),
    ]
