# Generated by Django 5.2.4 on 2025-07-06 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_user_moviecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecollection',
            name='movies',
            field=models.ManyToManyField(to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='moviecollection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='movie.user'),
        ),
    ]
