# Generated by Django 5.2.4 on 2025-07-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_moviecollection_movies_alter_moviecollection_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='movie.user'),
        ),
    ]
